#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZebraPrinter.WPF.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TwelveInventory")]
	public partial class MasterArticleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MasterArticleDataContext() : 
				base(global::ZebraPrinter.WPF.Properties.Settings.Default.TwelveInventoryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MasterArticleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterArticleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterArticleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasterArticleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vw_MasterArticle> Vw_MasterArticles
		{
			get
			{
				return this.GetTable<Vw_MasterArticle>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vw_MasterArticle")]
	public partial class Vw_MasterArticle
	{
		
		private int _Id;
		
		private System.Nullable<int> _ProductId;
		
		private string _GenericName;
		
		private string _CategorieCode;
		
		private string _BrandName;
		
		private string _ModelName;
		
		private string _ModelCode;
		
		private System.Nullable<int> _ProductTypeId;
		
		private string _UnitName;
		
		private string _ProductCode;
		
		private string _GroupName;
		
		private string _GroupCode;
		
		private string _ProductDescription;
		
		private string _PackSize;
		
		private string _Dimension;
		
		private string _WarrantyTerms;
		
		private System.Nullable<decimal> _AverageCost;
		
		private System.Nullable<int> _ColorID;
		
		private string _ColorName;
		
		private System.Nullable<int> _SizeID;
		
		private string _SizeName;
		
		private string _Sku;
		
		private string _Barcode;
		
		private decimal _CPU;
		
		private decimal _RPU;
		
		private System.Nullable<int> _BuId;
		
		private string _ProductTypeName;
		
		private string _CategoryName;
		
		private string _ProductName;
		
		private System.Nullable<int> _CategoryID;
		
		private System.Nullable<int> _GroupID;
		
		private System.Nullable<int> _BrandID;
		
		private System.Nullable<int> _GenericID;
		
		private System.Nullable<int> _ModelID;
		
		private System.Nullable<int> _UOMId;
		
		private System.Nullable<int> _ProdDetailsID;
		
		private System.Nullable<int> _UserBsnMappingId;
		
		private System.Nullable<bool> _IsQc;
		
		private System.Nullable<int> _QcFormId;
		
		private System.Nullable<int> _SubCategoryID;
		
		private string _SubCategoryName;
		
		private System.Nullable<int> _ServerPkId;
		
		private System.Nullable<bool> _IsActive;
		
		private string _Remarks;
		
		private System.Nullable<decimal> _VatPercent;
		
		public Vw_MasterArticle()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductId", DbType="Int")]
		public System.Nullable<int> ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				if ((this._ProductId != value))
				{
					this._ProductId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenericName", DbType="NVarChar(MAX)")]
		public string GenericName
		{
			get
			{
				return this._GenericName;
			}
			set
			{
				if ((this._GenericName != value))
				{
					this._GenericName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategorieCode", DbType="NVarChar(MAX)")]
		public string CategorieCode
		{
			get
			{
				return this._CategorieCode;
			}
			set
			{
				if ((this._CategorieCode != value))
				{
					this._CategorieCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="NVarChar(MAX)")]
		public string BrandName
		{
			get
			{
				return this._BrandName;
			}
			set
			{
				if ((this._BrandName != value))
				{
					this._BrandName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelName", DbType="NVarChar(MAX)")]
		public string ModelName
		{
			get
			{
				return this._ModelName;
			}
			set
			{
				if ((this._ModelName != value))
				{
					this._ModelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelCode", DbType="NVarChar(MAX)")]
		public string ModelCode
		{
			get
			{
				return this._ModelCode;
			}
			set
			{
				if ((this._ModelCode != value))
				{
					this._ModelCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeId", DbType="Int")]
		public System.Nullable<int> ProductTypeId
		{
			get
			{
				return this._ProductTypeId;
			}
			set
			{
				if ((this._ProductTypeId != value))
				{
					this._ProductTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitName", DbType="NVarChar(MAX)")]
		public string UnitName
		{
			get
			{
				return this._UnitName;
			}
			set
			{
				if ((this._UnitName != value))
				{
					this._UnitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCode", DbType="NVarChar(MAX)")]
		public string ProductCode
		{
			get
			{
				return this._ProductCode;
			}
			set
			{
				if ((this._ProductCode != value))
				{
					this._ProductCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(MAX)")]
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this._GroupName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCode", DbType="NVarChar(MAX)")]
		public string GroupCode
		{
			get
			{
				return this._GroupCode;
			}
			set
			{
				if ((this._GroupCode != value))
				{
					this._GroupCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductDescription", DbType="NVarChar(MAX)")]
		public string ProductDescription
		{
			get
			{
				return this._ProductDescription;
			}
			set
			{
				if ((this._ProductDescription != value))
				{
					this._ProductDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackSize", DbType="NVarChar(MAX)")]
		public string PackSize
		{
			get
			{
				return this._PackSize;
			}
			set
			{
				if ((this._PackSize != value))
				{
					this._PackSize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimension", DbType="NVarChar(MAX)")]
		public string Dimension
		{
			get
			{
				return this._Dimension;
			}
			set
			{
				if ((this._Dimension != value))
				{
					this._Dimension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarrantyTerms", DbType="NVarChar(MAX)")]
		public string WarrantyTerms
		{
			get
			{
				return this._WarrantyTerms;
			}
			set
			{
				if ((this._WarrantyTerms != value))
				{
					this._WarrantyTerms = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageCost", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AverageCost
		{
			get
			{
				return this._AverageCost;
			}
			set
			{
				if ((this._AverageCost != value))
				{
					this._AverageCost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorID", DbType="Int")]
		public System.Nullable<int> ColorID
		{
			get
			{
				return this._ColorID;
			}
			set
			{
				if ((this._ColorID != value))
				{
					this._ColorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColorName", DbType="NVarChar(MAX)")]
		public string ColorName
		{
			get
			{
				return this._ColorName;
			}
			set
			{
				if ((this._ColorName != value))
				{
					this._ColorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeID", DbType="Int")]
		public System.Nullable<int> SizeID
		{
			get
			{
				return this._SizeID;
			}
			set
			{
				if ((this._SizeID != value))
				{
					this._SizeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeName", DbType="NVarChar(MAX)")]
		public string SizeName
		{
			get
			{
				return this._SizeName;
			}
			set
			{
				if ((this._SizeName != value))
				{
					this._SizeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sku", DbType="NVarChar(MAX)")]
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				if ((this._Sku != value))
				{
					this._Sku = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(MAX)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="Decimal(18,2) NOT NULL")]
		public decimal CPU
		{
			get
			{
				return this._CPU;
			}
			set
			{
				if ((this._CPU != value))
				{
					this._CPU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPU", DbType="Decimal(18,2) NOT NULL")]
		public decimal RPU
		{
			get
			{
				return this._RPU;
			}
			set
			{
				if ((this._RPU != value))
				{
					this._RPU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuId", DbType="Int")]
		public System.Nullable<int> BuId
		{
			get
			{
				return this._BuId;
			}
			set
			{
				if ((this._BuId != value))
				{
					this._BuId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTypeName", DbType="NVarChar(MAX)")]
		public string ProductTypeName
		{
			get
			{
				return this._ProductTypeName;
			}
			set
			{
				if ((this._ProductTypeName != value))
				{
					this._ProductTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(MAX)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="NVarChar(MAX)")]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this._ProductName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="Int")]
		public System.Nullable<int> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="Int")]
		public System.Nullable<int> GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this._GroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandID", DbType="Int")]
		public System.Nullable<int> BrandID
		{
			get
			{
				return this._BrandID;
			}
			set
			{
				if ((this._BrandID != value))
				{
					this._BrandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenericID", DbType="Int")]
		public System.Nullable<int> GenericID
		{
			get
			{
				return this._GenericID;
			}
			set
			{
				if ((this._GenericID != value))
				{
					this._GenericID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="Int")]
		public System.Nullable<int> ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this._ModelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UOMId", DbType="Int")]
		public System.Nullable<int> UOMId
		{
			get
			{
				return this._UOMId;
			}
			set
			{
				if ((this._UOMId != value))
				{
					this._UOMId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdDetailsID", DbType="Int")]
		public System.Nullable<int> ProdDetailsID
		{
			get
			{
				return this._ProdDetailsID;
			}
			set
			{
				if ((this._ProdDetailsID != value))
				{
					this._ProdDetailsID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserBsnMappingId", DbType="Int")]
		public System.Nullable<int> UserBsnMappingId
		{
			get
			{
				return this._UserBsnMappingId;
			}
			set
			{
				if ((this._UserBsnMappingId != value))
				{
					this._UserBsnMappingId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsQc", DbType="Bit")]
		public System.Nullable<bool> IsQc
		{
			get
			{
				return this._IsQc;
			}
			set
			{
				if ((this._IsQc != value))
				{
					this._IsQc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QcFormId", DbType="Int")]
		public System.Nullable<int> QcFormId
		{
			get
			{
				return this._QcFormId;
			}
			set
			{
				if ((this._QcFormId != value))
				{
					this._QcFormId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryID", DbType="Int")]
		public System.Nullable<int> SubCategoryID
		{
			get
			{
				return this._SubCategoryID;
			}
			set
			{
				if ((this._SubCategoryID != value))
				{
					this._SubCategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCategoryName", DbType="NVarChar(MAX)")]
		public string SubCategoryName
		{
			get
			{
				return this._SubCategoryName;
			}
			set
			{
				if ((this._SubCategoryName != value))
				{
					this._SubCategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServerPkId", DbType="Int")]
		public System.Nullable<int> ServerPkId
		{
			get
			{
				return this._ServerPkId;
			}
			set
			{
				if ((this._ServerPkId != value))
				{
					this._ServerPkId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NVarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VatPercent", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VatPercent
		{
			get
			{
				return this._VatPercent;
			}
			set
			{
				if ((this._VatPercent != value))
				{
					this._VatPercent = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
